var locations = [
  "Aberdeen",
  "Aberuth",
  "Aberyst",
  "Abingdon",
  "Accreton",
  "Aeredale",
  "Airedale",
  "Alnerwick",
  "Ampleforth",
  "Anghor",
  "Anponi",
  "Appleby",
  "Aquarin",
  "Aramoor",
  "Aria",
  "Arkala",
  "Aroon",
  "Ascot",
  "Ashborne",
  "Astrakane",
  "Atoll",
  "Axminster",
  "Aylesbury",
  "Ayrith",
  "Azmar",
  "Azure Tower",
  "Ballinam",
  "Balmoral",
  "Barcom",
  "Bardford",
  "Barkamsted",
  "Barnsley",
  "Berxley",
  "Black Hallows",
  "Blackburn",
  "Blackpool",
  "Blackridge",
  "Blencathra",
  "Breedon",
  "Brickel",
  "Bromwich",
  "Bullmar",
  "Burnsley",
  "Bury",
  "Butterpond",
  "Cappadoc",
  "Cardend",
  "Chesterfield",
  "Cirencester",
  "Clacton",
  "Clarcton",
  "Crasmere",
  "Craydon",
  "Creed Caverns",
  "Crullfeld",
  "Dalery",
  "Dalhurst",
  "Dalmerlington",
  "Damerel",
  "Deathfall",
  "Desia",
  "Dewhurst",
  "Dewsbury",
  "Dornwich",
  "Doveport",
  "Dragontail",
  "Draycott",
  "Dread Field",
  "Durnatel",
  "Eastbourne",
  "Eldheim",
  "Ely",
  "Erast",
  "Everwinter",
  "Fallk",
  "Fanfoss",
  "Farnworth",
  "Fern",
  "Firebend",
  "Fool's March",
  "Foolshope",
  "Fortune Plains",
  "Fournemouth",
  "Frogheo",
  "Frucso",
  "Garrigill",
  "Glanchester",
  "Gloom",
  "Goldenleaf",
  "Goulcrest",
  "Grimsby",
  "Hadleigh",
  "Haling Cove",
  "Hallow",
  "Hampstead",
  "Hankala",
  "Haran",
  "Harmstead",
  "Harnsey",
  "Harthwaite",
  "Hewe",
  "Hirane",
  "Holmfirth",
  "Hope",
  "Horndean",
  "Hullbeck",
  "Inver",
  "Ironhaven",
  "Itjok",
  "Jade",
  "Kald",
  "Kalmani",
  "Kameer",
  "Kara's Vale",
  "Keld",
  "Kelna",
  "King's Watch",
  "Kinship Tower",
  "Kirkwall",
  "Knife's Edge",
  "Kuuma",
  "Lakeshore",
  "Landow",
  "Langdale",
  "Larcbost",
  "Larking",
  "Lerwick",
  "Lhanbryde",
  "Ivywood",
  "Livohka",
  "Llyne",
  "Lockinge",
  "Louhil",
  "Lowestoft",
  "Macclesfield",
  "Marren's Eve",
  "Martslock",
  "Mensfield",
  "Merton",
  "Meteli",
  "Miracle Creek",
  "Mirefield",
  "Moonbright",
  "Moor",
  "Morass",
  "Mossley",
  "Mountmend",
  "Mournstead",
  "Murkwell",
  "Murlayfield",
  "Mystery Den",
  "Nancledra",
  "Naporia",
  "Nerton",
  "Norfolk",
  "Northwich",
  "Nuxvar",
  "Oakheart",
  "Obelisk",
  "Old Ashton",
  "Openshaw",
  "Orkney",
  "Ormskirk",
  "Orrinshire",
  "Ozryn",
  "Padstow",
  "Parik",
  "Pathstow",
  "Penkurth",
  "Penshaw",
  "Pinnella Pass",
  "Pomovara",
  "Porthcrawl",
  "Portsmouth",
  "Qezu",
  "Quiet Wilds",
  "Ramshorn",
  "Redwater",
  "Risteys",
  "Romsey",
  "Roselake",
  "Rune Grotto",
  "Runswick",
  "Rust Fen",
  "Sanlow",
  "Satbury",
  "Saxondale",
  "Sharnwick",
  "Sheffield",
  "Skegness",
  "Snow Cave",
  "Solaris",
  "Solime",
  "Soqa",
  "South Warren",
  "Spalding",
  "Spire",
  "Spring Meadow",
  "Squall's End",
  "Steel",
  "Sutton",
  "Swindmore",
  "Swordbreak",
  "Symbiosis Tower",
  "Tardide",
  "Tarnstead",
  "Tarrin",
  "Tergaron",
  "Thanos",
  "The Dead Zone",
  "The Unwelcoming Expanse",
  "Thorpeness",
  "Three Streams",
  "Todmorden",
  "Trirniq",
  "Troutbeck",
  "Trudid",
  "Tundra",
  "Varis",
  "Velvet",
  "Venom Dune",
  "Veritas",
  "Waekefield",
  "Walden",
  "Warrington",
  "Watford",
  "Westray",
  "Westwend",
  "Willowdale",
  "Wingston",
  "Wolf Lagoon",
  "Woolhope",
  "Yarrin",
  "Zalfari"
];

var aberdeen = {
  type: "city",
  name: "waterbrook",
  description: "Deepmere has been a calm city that has been kept safe because of dwarfs for quiet some time. It's a business heavy place and the stuff you do there is mostly fair, as guards roam the entire city. It's still a bit new but because of dwarven ingenuity it seems to have grown in a very fast paste.",
  population: "1651",
  defense: "Stone",
  laws: "H / L",
  corruption: "None",
  military: "120, lvl.6",
  resources: "Armor & weapons",
  wealth: "L",
  behaviour: "Welcoming",
  religions: "Dwarven"
};
